on:
    push:
        branches: [ develop ]
permissions: 
    contents: write
    pull-requests: write  
name: create-pull-request workflow
jobs:
    createPullRequest:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          name: checkout
        - name: create pull request
          run: gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}