on:
    push:
        branches: [ develop ]
name: create-pull-request workflow
jobs:
    createPullRequest:
      runs-on: ubuntu-latest
      steps:
        - name: create pull request
          run: gh pr create -B main -H develop --title 'Merge develop into main' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}